export default [
    "Smell ya later 👃",
    "Until fate reunites us… or tomorrow 😌",
    "Farewell, mortal (I’ll text you later)",
    "I take my leave… dramatically 🎭",
    "Goodbye… don’t forget me (you won’t)",
    "I vanish now—act surprised",
    "This is where our paths diverge… for like 2 hours",
    "I must go, my people need me",
    "I disappear into the void… brb 🌌",
    "Farewell… try not to cry too much 😏",
    "I’m off—remember me as a legend",
    "Until we meet again… probably soon",
    "I fade into the shadows 🕶️",
    "Goodbye, peasants (affectionate)",
    "I take my final bow—applause please 🎤",
    "I leave you now… in suspense",
    "Gone like I was never here (I was)",
    "I exit stage left—gracefully",
    "Farewell… stay out of trouble (or don’t)",
    "I’m out—cue dramatic music 🎶",
    "I’m leaving now—try to cope",
    "Goodbye… this is very emotional for me (it’s not)",
    "I go now—remember everything I said",
    "I must depart—no autographs please",
    "I’m gone—contain your sadness",
    "Farewell… yes, this is a big moment",
    "I leave—hold your applause",
    "I disappear—this is my villain arc",
    "I’m out—plot twist complete",
    "Goodbye… I expect to be missed",
    "Until destiny calls me again 📞",
    "I walk into the horizon 🌅",
    "This chapter ends… the sequel soon",
    "I leave this realm for now",
    "I drift into legend",
    "Farewell… the story continues elsewhere",
    "I step into the unknown (aka my room)",
    "The journey takes me onward",
    "I fade… but not really",
    "Until the next episode 🎬"
]